import numpy as np
arr = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])

arr3 = np.add(arr,arr2)
print(arr3)
print(arr+5)
print(arr+arr2)
print(arr.__add__(5))
print(arr.__add__(arr2))
print()
arr3 = np.subtract(arr,arr2)
print(arr3)
print(arr-5)
print(arr-arr2)
print(arr.__sub__(5))
print(arr.__sub__(arr2))
print()
arr3 = np.multiply(arr,arr2)
print(arr3)
print(arr*5)
print(arr*arr2)
print(arr.__mul__(5))
print(arr.__mul__(arr2))
print()
arr3 = np.divide(arr,arr2)
print(arr3)
print(arr/5)
print(arr/arr2)
print(arr.__truediv__(5))
print(arr.__rtruediv__(5)) # ye reverse kerta hai division method ko mean ye arr/5 nh 5/arr kare ga
print(np.divide(arr,5))
print(np.divide(arr,arr2))
print()
arr3 = np.mod(arr,arr2)
print(arr3)
print(arr%5)
print(arr%arr2)
print(arr.__mod__(5))
print(arr.__mod__(arr2))
print()
arr3 = np.reciprocal(arr,arr2)
print(arr3)
print(1/arr)
print(1/5)
print()

arr = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
arr3 = np.power(arr,arr2)
print(arr3)
print(arr**5)
print(arr**arr2)
print(arr.__pow__(5))
print(arr.__pow__(arr2))
print()

